#!/bin/bash

if [ "x$DOCKER_HOST" == "x" ]; then
  if (( $UID == 0 )); then
    DOCKER_HOST="unix:///run/podman/podman.sock"
  else
    DOCKER_HOST="unix:///run/user/$UID/podman/podman.sock"
  fi
  export DOCKER_HOST
fi

exec /usr/local/bin/docker-compose-linux-$(uname -m) $@
